apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: iu5devops-loki
    access: proxy
    url: http://iu5devops-loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: iu5devops-jaeger
          name: JaegerTraceID
          matcherRegex: trace_id=(\w+)
          url: '$${__value.raw}'
        - name: TraceID
          matcherRegex: trace_id=(\w+)
          url: 'http://localhost:16686/trace/$${__value.raw}'
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: iu5devops-prometheus
    url: http://iu5devops-prometheus:9090
  - name: Jaeger
    type: jaeger
    uid: iu5devops-jaeger
    url: http://iu5devops-jaeger:16686
    access: proxy
    readOnly: false
    isDefault: false
